services:
  - docker
env:
  - PROJECT=keystone PROJECT_REF="master" PROFILES="apache ldap" PIP_EXTRA_PACKAGES="python-openstackclient"
  - PROJECT=glance PROJECT_REF="master" PROFILES="ceph" PIP_EXTRA_PACKAGES="python-swiftclient"
  - PROJECT=cinder PROJECT_REF="master" PROFILES="lvm qemu ceph" PIP_EXTRA_PACKAGES="python-swiftclient"
  - PROJECT=nova PROJECT_REF="master" PROFILES="ceph linuxbridge openvswitch configdrive qemu apache" PIP_EXTRA_PACKAGES=""
  - PROJECT=neutron PROJECT_REF="master" PROFILES="linuxbridge openvswitch" PIP_EXTRA_PACKAGES=""
  - PROJECT=heat PROJECT_REF="master" PROFILES="apache" PIP_EXTRA_PACKAGES=""
  - PROJECT=horizon PROJECT_REF="master" PROFILES="apache" PIP_EXTRA_PACKAGES=""

  - PROJECT=keystone PROJECT_REF="stable/rocky" PROFILES="apache ldap" PIP_EXTRA_PACKAGES="python-openstackclient"
  - PROJECT=glance PROJECT_REF="stable/rocky" PROFILES="ceph" PIP_EXTRA_PACKAGES="python-swiftclient"
  - PROJECT=cinder PROJECT_REF="stable/rocky" PROFILES="lvm qemu ceph" PIP_EXTRA_PACKAGES="python-swiftclient"
  - PROJECT=nova PROJECT_REF="stable/rocky" PROFILES="ceph linuxbridge openvswitch configdrive qemu apache" PIP_EXTRA_PACKAGES=""
  - PROJECT=neutron PROJECT_REF="stable/rocky" PROFILES="linuxbridge openvswitch" PIP_EXTRA_PACKAGES=""
  - PROJECT=heat PROJECT_REF="stable/rocky" PROFILES="apache" PIP_EXTRA_PACKAGES=""
  - PROJECT=horizon PROJECT_REF="stable/rocky" PROFILES="apache" PIP_EXTRA_PACKAGES=""
script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker build --no-cache --force-rm --build-arg PROJECT="${PROJECT}" --build-arg PROJECT_REF="${PROJECT_REF}" --build-arg PROFILES="${PROFILES:-}" --build-arg PIP_EXTRA_PACKAGES="${PIP_EXTRA_PACKAGES:-}" -f Dockerfile.opensuse_15 -t evrardjp/${PROJECT}:${PROJECT_REF#*/} .
  - docker push ${DOCKER_USERNAME}/${PROJECT}:${PROJECT_REF#*/}
matrix:
  fast_finish: true
